# Generated by Django 3.2.8 on 2022-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.TextField(unique=True)),
                ('dv', models.TextField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('merchant_registration', models.TextField()),
                ('img', models.ImageField(default='Profile_Client/foto.jpg', upload_to='Photo_Client')),
            ],
        ),
    ]
