# Generated by Django 3.2.8 on 2022-04-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('data', '0003_payroll_type_document_identification_type_contract_type_worker'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='client',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.municipality'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_documentI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_document_identification'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_regime'),
        ),
    ]
