# Generated by Django 3.2.8 on 2022-04-05 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0003_payroll_type_document_identification_type_contract_type_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentIdentification', models.TextField(unique=True)),
                ('business_name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('certificate_generation_date', models.CharField(max_length=10)),
                ('certificate_expiration_date', models.CharField(max_length=10)),
                ('resolution_generation_date', models.CharField(max_length=10)),
                ('resolution_expiration_date', models.CharField(max_length=10)),
                ('block', models.BooleanField(default=False)),
                ('token', models.TextField()),
                ('user', models.TextField()),
                ('password', models.TextField()),
                ('logo', models.ImageField(default='Logo_Company/default.png', upload_to='Logo_Company')),
                ('cod_bars', models.BooleanField(default=True)),
                ('resolution_number', models.TextField(default='18760000001')),
                ('prefix', models.TextField(default='SETP')),
                ('license', models.BooleanField(default=False)),
                ('date_register', models.TextField(default=datetime.date(2022, 4, 5))),
                ('payment_date', models.TextField(default=datetime.date(2022, 4, 5))),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.municipality')),
                ('type_documentI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_document_identification')),
                ('type_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_organization')),
                ('type_regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_regime')),
            ],
        ),
    ]
